### PR TITLE
Create a node/express app skeleton

### LINKED ISSUE #1: Create a node/express app skeleton
Please create a basic nodejs/express skeleton with these additional requirements:
- Prepare for multi router files, i.e. not the way where all routing is done in the app.js file
- Connect to a mongodb in app.js, either to `process.env.MONGOLAB_URI` if present, or to a db named `ttt-slack` on the localhost, if not.
- Wrap the mongo connection in [monk](https://github.com/Automattic/monk)
- Make it available to all the routers so they don't have to create another connection (either via app variable, or any other way you think is suitable)
- Add an empty router named `slack` on `/slack`
- Make sure not to commit the `node_modules` directory. Add it to `.gitignore`
- Make a `procfile` so it can be deployed to Heroku 

codemill$10

### PR DESCRIPTION
**Pull request by khuongduybui**
codemill-id-56eb1c3bc2e7d70300f702a7 fixes #1

### CODE REVIEW

**Comment by shaharsol** [comment]
@khuongduybui thanks for the PR, I will have a look and test later today. In a brief browse via the code all looks OK, just saw a missing default mongo port from the dev uri. Can't remember what it is...

**Comment by shaharsol** [comment]
@khuongduybui Ok, started testing. 
I'm getting this error:

```
/Users/shaharsol/git/ttt-slack/routes/slack.js:8
  db.get('users').find({}, (err, docs) => {
                                        ^
SyntaxError: Unexpected token >

```

**Comment by khuongduybui** [comment]
Default mongo port is `27017`.
That syntax is anonymous, non-scoped function in ES2015. Try it with NodeJS 5.x.
In case you need to use legacy versions of Node, I can downgrade the code.

**Comment by shaharsol** [comment]
Oh I didn't know that. I'm running a lower node version locally as I need
to support 4.x. Yes please downgrade and also can you add the mongo port?

**Comment by khuongduybui** [comment]
I can add the port in, but can you tell me why you want to explicitly set the "default" port to default value? Did it not work when you were testing because it picked the wrong port, or throw an error about not having a port?

**Comment by shaharsol** [comment]
Oh, if it works this way then it's fine. I assumed it'll fail but didn't
get that far.

**Comment by shaharsol** [comment]
Thanks @khuongduybui, It's been pleasure working with you. I'll add some more tasks for this project tomorrow. I'll ping you with links so you can take them if you want.

**Pull request merged**
