### PR TITLE
slack integration

### LINKED ISSUE #3: Create a Slack command integration
The objective is to enable our company's employees to report their working hours via simple Slack command.

The backend for reporting working hours is an [Anuko Time Tracker](https://timetracker.anuko.com) that is installed on our premises. For the development process I have created a test account in the hosted version of Anuko.
url: https://timetracker.anuko.com/login.php
username: ttt-slack-staging
password: 12345678
You'll find a single project, and two tasks that you can use to report time with.

The Anuko system is a rather old, API-less system, so we have built a proxy server that enables sending time tracking commands to it. For the development process I have deployed such a proxy server that runs against the Anuko hosted version.
url: https://ttt-proxy-staging.herokuapp.com/

the proxy server has a single command -- `/track-time` -- and here's how to use it:

```
curl -X POST -d "login=ttt-slack-staging" -d "password=12345678" -d "project=ttt-slack" -d "task=consulting" -d "start=09:00" -d "finish=10:00" -d "date=2016-03-12" -d "note=hello" https://ttt-proxy-staging.herokuapp.com/track-time
```

On success, the proxy will return http 200, otherwise it returns 500 with an error message.

Your task is to implement these features:

`/ttt username {username}` to save the users' Anuko username in the database
`/ttt password {username}` to save the users' Anuko password in the database
`/ttt project {project-name}` to save the users' default project in the database
`/ttt task {task-name}` to save the users' default task in the database
`/ttt in` to be used by the user to mark a beginning of a day. Save the current time in the database
`/ttt out` to post a time tracking to Anuko, based on all the information that is already saved in the database, and the current date.
`/ttt track {project-name} {task-name} {in-time} {out-time}` for cases where the default project and task are not to be used, or for any other reason, for example the user forgot to `/ttt in` when they entered their office in the morning :)

Of course the unique username you should use for identifying users will be the one provided by Slack. Please always respond an ephemeral human readable response. For example, After a successful saving of a default project, let the user know it was successful. If there was a problem with tracking the working hours, the employee should be alerted about it. 

Please make the proxy server endpoint configurable via ENV vars, i.e. `process.env.TTT_PROXY_URI`

codemill$60

### PR DESCRIPTION
**Pull request by blitmap**
codemill-id-56efa809eb8038030069d169 fixes #3

This is still a bit messy, looking for advice on cleanliness/organization.  :smile:

I added 2 dependencies to `package.json`.  `moment` to make it easy to parse the start/stop time from Slack, and `request` for easier `POST`ing

### CODE REVIEW

**Comment by shaharsol** [comment]
Thanks @blitmap I'll be able to test it in a few hours. For this particular project, I don't really care about messy code if it's working.

**Comment by blitmap** [comment]
Sure thing - I had fun!  Took me quite a few hours, but I learned some things along the way.  :smile:

**Comment by shaharsol** [comment]
@blitmap Ok, had a quick look and started running. From the the looks the code looks OK, not messy at all.

There are few errors to start with, like you need to replace `===` with `!==` in slack.js line 76... 
Also, on line 114 the `[command]` doesn't compile. You need to build a JS object dynamically I guess. i.e.

```
var set = {}
set['project'] = args[0]
users.findAndModify(
      { id: id }, // query
      { $set: set }, // update
      { new: true, upsert: true }, // return most-current, insert if non-existent
      function (err, data) {
        res.send(userStatus(data));
      }
    );
```

I stopped here. All in all the code looks OK but I hoped that when I integrate with Slack it will just run... and it didn't. You want to make it run?

Also a general note as you mentioned you're not used to web apps, instead of a `return` when the unexpected occurs, better `res.status(500).send('token doesn\'t match');`

So what do you say? I hate to just throw it away because you can definitely code, but I need it to work out of the box...

**Comment by blitmap** [comment]
@shaharsol I can fix those issues. :smile:

**Comment by shaharsol** [comment]
@blitmap sweet! Can you please create a demo slack team so you can test it yourself to see if works out of the box before your next update to this PR?

**Comment by shaharsol** [comment]
@blitmap also ctrl+f for "Delayed responses and multiple responses" in [this page of the Slack Docs](https://api.slack.com/slash-commands)

**Comment by blitmap** [comment]
I've been testing it on one of the Slack teams I'm joined to - I just committed a few typos by accident, haha.  If you log into the Anuko proxy you can see a few of the `POST`s I got through - I'm working on the delayed response part right now. :smile:

**Comment by blitmap** [comment]
I'm not certain but I think I need these `return`s.  If I do:

``` javascript
res.send('cat');
res.send('dog');
```

... it would complain about a double-send(), if I don't return afterward I continue on to other res.send()'s.  You want me to return `500` on error to Slack?

**Comment by shaharsol** [comment]
Oh, well if you do a `res.send` before you return then it's fine. I just noticed a `return` without a `res.send` in the token verification at the area of line 76, and I didn't follow to see if it's persistent, I just assumed it's the way you did them all...

**Comment by blitmap** [comment]
Ahh -- for that particular 1 I think it's important the incoming `POST` be ignored because we can't verify it's from Slack (it doesn't have the Slack token).  Would you rather I send 403 Forbidden back?

**Comment by shaharsol** [comment]
Good idea

**Comment by blitmap** [comment]
Sorry if I'm going a bit slowly - I'm still stuck on the delayed acknowledgement back to Slack to show that the `POST` to Anuko was successful.  Slack keeps saying 'invalid_payload' so I must be preparing my JSON wrong.  After this it's the precomputed property issue `[command]`

**Comment by blitmap** [comment]
Just FYI I'm starting the project like this when I'm testing on Slack:

``` bash
TTT_PROXY_URI='https://ttt-proxy-staging.herokuapp.com/track-time' SLACK_TOKEN=cmxlP0LjJCK3JrdmrX45SVut npm start
```

I'm used to putting those env vars in a file like `.env` that gets hidden from git.  Then doing:

``` bash
source ./.env
npm start
```

**Comment by shaharsol** [comment]
@blitmap I started testing again but it seems like you're still pushing commits right? can u pls ping me when it's ready?

**Comment by blitmap** [comment]
@shaharsol I think it's done - I just squashed all my commits

I changed something important: When you `/ttt out` or `/ttt track...` (which triggers a post to anuko) it now clears the current task and start time in Mongo so afterward you have to specify a new task and start it (with `/ttt in`).  Before it would keep the old task and start time, without making you re-specify it.  Project persists unless changed of course.

It might also be worthwhile to rename `/ttt (in|out)` to `/ttt (start|finish)` so they match Anuko.

Anyway, let me know what you think.  If you have a Slack team to join I could demonstrate it for you, but this should be pretty straightforward.  :smile:

PS: I added a `/ttt note ...`, I know that wasn't in your list - I hope that's okay

**Comment by shaharsol** [comment]
@blitmap I'm getting:

```
TypeError: Object username,password,project,task,in has no method 'find'
    at readyForAnuko (/Users/shaharsol/git/ttt-slack/routes/slack.js:85:62)
```

either on `/ttt track`or `/ttt out`

**Comment by blitmap** [comment]
I also notice the date-checking in `/ttt track ...` is broken doing: `moment().fromNow().format(...)`

Let me look into these...

**Comment by shaharsol** [comment]
@blitmap I'm not using the latest version of node, can that be the reason? Maybe you used a ECMAScript 2015 notation?

**Comment by blitmap** [comment]
You are totally right - let me code up a non-ES6 version of `readyForAnuko()` real quick

**Comment by shaharsol** [comment]
@blitmap maybe u can use underscore.js

**Comment by blitmap** [comment]
@shaharsol okay, substituted the `Array::find()` use and fixed the date handling :smile:

**Comment by shaharsol** [comment]
@blitmap it works much better now!
2 bugs:
1. It clears the `task` after each report. I need to it to keep saving the default task forever, or until changed. The idea is that ppl will config the defaults and then mostly use `/ttt in` and `/ttt out`
2. `/ttt in` and `/ttt out` did work to the extent the data was logged in Anuko, however `/ttt track` didn't log data in Anuko though it reported back as if it did.

If u can pls solve these 2 and I'll merge.

**Comment by blitmap** [comment]
1) Okay, first 1 I can undo - I thought I was being clever :smile:

2) This one I believe is a problem with Anuko - we have so many tasks added whatever we POST is likely to overlap with existing, recorded tasks.  Anuko still accepts overlapping tasks even if it doesn't actually record it - I have no way to tell if the task was truly accepted or not. :(

3) I think there are still problems with `/ttt track` and date handling - I'm digging into it now.  Very strange - it reports the `finish-time` is of a bad format when it should first report the `start-time`.

**Comment by blitmap** [comment]
@shaharsol Should I only clear the `start-time` ?  Should `note` persist like `task`?

**Comment by shaharsol** [comment]
No, `note` shouldnt persist

**Comment by shaharsol** [comment]
@blitmap not sure which timezone you're in, but I must go to sleep now at GMT+2... I'll check back in the (my) morning. Hopefully I'll find your final commit ;-)

**Comment by blitmap** [comment]
@shaharsol Yeah sorry, I'm just hung up on this date thing - no problem, you get some sleep :smile:

The problem is moment.js is parsing 'cat' as a valid time.  This is all of my wat.

**Comment by blitmap** [comment]
@shaharsol Okay.  I think it is finally there.

1)  I ran through the date handling a bunch of different ways, I think it's fixed.  The problem was moment.js was doing a relaxed parse on 'cat' - so it was interpreting 'a' as 'am/AM' while ignoring 'c' and 't'.  I changed that to strict parsing and we're all good.

2) The 2nd part is something I can't really fix.  If I try to add a scheduled item to Anuko and it overlaps something that already exists, Anuko will still reply with status 200 and 'time tracked'.  I have no way to determine if it's accepting and silently discarding it.  I believe this is a shortcoming of Anuko  :(

3) I used `426 Precondition Required` for the places where we need the user to set more info before `POST`ing.  I hope that's appropriate - I've never actually used 426 before.

Duuuuuude this was all so much fun!  I had a lot of fun, I hope you got what you were looking for!  Let me know if you need me to fix anything else, I had a blast figuring this out!

Looking forward to your merge if you approve.  ^___^

PS: I am on Pacific Time (PST/PDT).  Now is my turn to sleep, haha

**Comment by shaharsol** [comment]
@blitmap Excellent it all works now! So fun to work with someone who enjoys coding so much!

**Comment by blitmap** [comment]
Thank you very much, sir - I had fun!  Would work for you again, 10/10 :smile:

**Pull request merged**
