### PR TITLE
help text, hide password, translate timezones, add date to track

### LINKED ISSUE #6: Fix several small issues with a Slack command integration
The original project is well described here: #3 

After a soft launch to several employees we received some feedback and require some minor modifications
1. A plain `/ttt` should response with a help text describing the options of the command (like a `--help` of a command line)
2. Please don't show the password in plain text for the user. Mark *****\* for an existing password.
3. Our entire team is located at GMT+2 (actually its now GMT+3 because of DST but the system should be able to be aware to that), but the server time is GMT. So the `/in` and `/out` commands should work accordingly and not report everything as 2-3 hours earlier...
4. Add an optional {date} param as the last param for the `/track` command. Format should be yyyy-mm-dd.

codemill $20

### PR DESCRIPTION
**Pull request by blitmap**
codemill-id-56f91ed63c43fb0300541e4d fixes #6

Okay, so a few things need mentioning:

1) I added `moment-timezone` as a dependency in `package.json` to assist in translating from your local timezone to Anuko's [GMT] timezone.

2) I added the ability to set LOCAL_TIMEZONE and ANUKO_TIMEZONE in the environment and this will make use of it, otherwise it defaults to "Asia/Jerusalem" for the local and "GMT" for Anuko.

3) Because I used "Asia/Jerusalem" rather than "IDT" or "IST" it should automatically track daylight savings time. :smile:

4) I found a bug!  In my original contribution I cleared the "in-time" on both `/ttt out` and `/ttt track ...`.  I don't think this was correct.  As far as I know, `/ttt track ...` is issued unrelated to the current task.  It would be wrong to clear the 'in-time' of the current task if you're registering a separate task.  Correct?  I have added a new check to make sure it only clears the in-time in the Mongo database if you're doing `/ttt out`

5) This took me a while to test - I was confusing myself.  I was translating the date argument from local to "Anuko time" and it was making "2016-03-28" become "2016-03-27".  I didn't think it was registering the task because I was viewing 3/28, not 3/27.

Anyway, I hope this is everything you were looking for.  Please let me know if you need me to fix something! :smile:

### CODE REVIEW

**Comment by shaharsol** [comment]
@blitmap I'm sorry for not being quick this time, but it'll have to wait for tomorrow if that's OK with you.

**Comment by blitmap** [comment]
No complaints here - I understand you have a schedule. :smile:

**Comment by shaharsol** [comment]
Had to set the ANUKO_TIMEZONE. So smart of you to add this! Pleasure working with you!

**Comment by blitmap** [comment]
And thank you!  I had fun :smile:

**Pull request merged**
